#! /bin/sh
set -eu

PKGS=${PKGS:-$*}

export NIXPKGS_ALLOW_BROKEN=1
export NIXPKGS_ALLOW_UNFREE=1

export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/bfff24189cae0bf6eceacd5c3e4d8464ba72b895.tar.gz"









devtools="cabal-install"

case $PKGS in
	*.cabal)
		nix-shell -I 'nixpkgs=https://github.com/NixOS/nixpkgs/archive/f44165f484493fa42140fec252dfefcda6f6dda5.tar.gz' -p cabal2nix --run "cabal2nix --shell $(dirname $PKGS) --extra-arguments $(echo $devtools | sed 's/[ ]/ --extra-arguments /g') > /tmp/hs.nix"
		nix-shell -p bash --run "sed -i 's/executableHaskellDepends/buildDepends = with pkgs; [$devtools];\nexecutableHaskellDepends/' /tmp/hs.nix"
		if [[ ! $(grep 'buildDepends' /tmp/hs.nix) ]]; then
            nix-shell -p bash --run "sed -i 's/libraryHaskellDepends/buildDepends = with pkgs; [$devtools];\nlibraryHaskellDepends/' /tmp/hs.nix"
        fi;
		nix-shell -p pkgconfig -p ctags --run "nix-shell /tmp/hs.nix --run 'cd $(dirname $PKGS) && cabal repl'"
		;;
	*)
		nix-shell -p pkgconfig -p ctags -p "haskellPackages.ghcWithPackages (p: with p; [$PKGS])" --run "ghci"
		;;
esac
