#! /bin/sh
set -eu

PKGS=${PKGS:-$*}
ARGS=${ARGS:-}
WITH_NIX_PATH=${WITH_NIX_PATH:-}

export NIXPKGS_ALLOW_BROKEN=1
export NIXPKGS_ALLOW_UNFREE=1

if [ "$WITH_NIX_PATH" != "" ]; then
	echo "Using given NIX_PATH: $WITH_NIX_PATH"
	export NIX_PATH="$WITH_NIX_PATH"
elif [ "$(uname -s)" = "Darwin" ]; then
    export NIX_PATH="nixpkgs=channel:nixpkgs-18.09-darwin"
    echo "Using darwin NIX_PATH: $NIX_PATH"
else
	export NIX_PATH="nixpkgs=channel:nixos-18.09"
	echo "Using standard NIX_PATH: $NIX_PATH"
fi








devtoolsNoOverride="stack intero Cabal cabal-install hdocs hasktags pointfree hdevtools stylish-haskell hindent hlint"
devtoolsOverride="hoogle process-extras apply-refact ghc-exactprint"
devtools="$devtoolsNoOverride (hoogle.override { process-extras = haskell.lib.dontCheck process-extras; }) (apply-refact.override { ghc-exactprint = haskell.lib.dontCheck ghc-exactprint; })"

case $PKGS in
	*.cabal)
		nix-shell -p cabal2nix --run "cabal2nix --shell $(dirname $PKGS) --extra-arguments $(echo $devtoolsNoOverride $devtoolsOverride | sed 's/[ ]/ --extra-arguments /g') > /tmp/hs.nix"
		nix-shell -p bash --run "sed -i 's/executableHaskellDepends/buildDepends = with pkgs; [$devtools];\nexecutableHaskellDepends/' /tmp/hs.nix"
        if [[ ! $(grep 'buildDepends' /tmp/hs.nix) ]]; then
            nix-shell -p bash --run "sed -i 's/libraryHaskellDepends/buildDepends = with pkgs; [$devtools];\nlibraryHaskellDepends/' /tmp/hs.nix"
        fi;
		nix-shell -p pkgconfig -p ctags --run "nix-shell $ARGS /tmp/hs.nix"
		;;
	*)
		nix-shell $ARGS -p pkgconfig -p ctags -p "haskellPackages.ghcWithPackages (p: with p; [$devtools $PKGS ])"
		;;
esac
