#! /bin/sh
set -eu

PKGS=${PKGS:-$*}

export NIXPKGS_ALLOW_BROKEN=1
export NIXPKGS_ALLOW_UNFREE=1

if [ "$(uname -s)" = "Darwin" ]; then
	opensublime="open -n -a 'Sublime Text'"
	export NIX_PATH="nixpkgs=https://nixos.org/channels/nixpkgs-17.09-darwin/nixexprs.tar.xz"
else
	opensublime="sublime"
	export NIX_PATH="nixpkgs=https://nixos.org/channels/nixos-17.09/nixexprs.tar.xz"
fi



devtoolsNoOverride="cabal-install hdocs hasktags pointfree hsdev hdevtools ghc-mod stylish-haskell hindent"
devtoolsOverride="hoogle apply-refact process-extras ghc-exactprint"
devtools="$devtoolsNoOverride (hoogle.override { process-extras = haskell.lib.dontCheck process-extras; }) (apply-refact.override { ghc-exactprint = haskell.lib.dontCheck ghc-exactprint; })"

case $PKGS in
	*.cabal)
		nix-shell -p cabal2nix --run "cabal2nix --shell $(dirname $PKGS) --extra-arguments $(echo $devtoolsNoOverride $devtoolsOverride | sed 's/[ ]/ --extra-arguments /g') > /tmp/hs.nix"
		nix-shell -p bash --run "sed -i 's/executableHaskellDepends/buildDepends = with pkgs; [$devtools];\nexecutableHaskellDepends/' /tmp/hs.nix"
		if [[ ! $(grep 'buildDepends' /tmp/hs.nix) ]]; then
			nix-shell -p bash --run "sed -i 's/libraryHaskellDepends/buildDepends = with pkgs; [$devtools];\nlibraryHaskellDepends/' /tmp/hs.nix"
		fi;
		nix-shell -p pkgconfig -p ctags --run "nix-shell /tmp/hs.nix --run \"$opensublime $(dirname $PKGS)\""
		;;
	*)
		nix-shell -p pkgconfig -p ctags -p "haskellPackages.ghcWithPackages (p: with p; [$devtools $PKGS ])" --run "$opensublime"
		;;
esac
